#!/bin/sh

JVM_PARAMS="-Duser.timezone=${TIME_ZONE}"
exec java "${JVM_PARAMS}" -jar /deployments/app.jar --PROFILE="${PROFILE}" --URL_DATABASE="${URL_DATABASE}" \
--USER_DATABASE="${USER_DATABASE}" --PASSWORD_DATABASE="${PASSWORD_DATABASE}" --SCHEMA_DATABASE="${SCHEMA_DATABASE}"