
quiz:
  quantidade_perguntas_por_quiz: 10
  tempo_maximo_duracao_quiz: 420
  pontuacao_resposta_correta: 100
  penalidade_resposta_incorreta: 0.1

server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}

spring:
  flyway:
    locations: classpath:db/migration
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATASOURCE_HOST}/${DATASOURCE_DATABASE}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html

management:
  health:
    probes:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health,prometheus,env'
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
    env:
      enabled: true