INSERT INTO quiz (id, nome) VALUES(1, 'Quiz BB Week Dungeons & Data');

    
        
INSERT INTO pergunta (ID, DESCRICAO) VALUES
(1, 'Você faz parte de uma equipe de ciência de dados que trabalha para uma rede nacional de fast-food. Você cria um relatório simples que mostra tendências: os clientes que visitam a loja com mais frequência e compram refeições menores gastam mais do que os clientes que visitam a loja com menos frequência e compram refeições maiores. Qual é o diagrama mais provável que sua equipe criou?'),
(2, 'Você trabalha para uma organização que vende serviços de filtragem de spam para grandes empresas. Sua organização deseja fazer a transição do produto para usar aprendizado de máquina. Atualmente é uma lista de 250.000 palavras-chave. Se uma mensagem contiver mais do que algumas dessas palavras-chave, ela será identificada como spam. Qual seria uma vantagem da transição para o aprendizado de máquina?'),
(3, 'Você trabalha em um serviço de streaming de música e deseja usar aprendizado de máquina supervisionado para classificar músicas em diferentes gêneros. Seu serviço coletou milhares de músicas de cada gênero e você usou isso como dados de treinamento. Agora você extrai um pequeno subconjunto aleatório de todas as músicas do seu serviço. Como é chamado esse subconjunto?'),
(4, 'Na programação de computadores tradicional, você insere comandos. O que você contribui com o aprendizado de máquina?'),
(5, 'Sua empresa deseja prever se os clientes existentes de seguros automotivos têm maior probabilidade de comprar seguros residenciais. Ele criou um modelo para prever melhor o melhor contato dos clientes sobre seguros residenciais, e o modelo tinha uma variância baixa, mas um viés alto. O que isso diz sobre o modelo de dados?'),
(6, 'Você deseja identificar padrões climáticos globais que podem ter sido afetados pelas mudanças climáticas. Para fazer isso, você deseja usar algoritmos de aprendizado de máquina para encontrar padrões que de outra forma seriam imperceptíveis para um meteorologista humano. Qual é o lugar para começar?'),
(7, 'Você trabalha em uma equipe de ciência de dados que deseja melhorar a precisão do resultado do K-nearest neighbor executando um resultado ingênuo de Bayes. Do que isso é um exemplo?'),
(8, '`____` analisa a relação entre os preditores e seu resultado.'),
(9, 'Qual é um exemplo de aplicação comercial para um sistema de aprendizado de máquina?'),
(11, 'Você trabalha para uma empresa de energia que possui centenas de milhares de medidores elétricos. Esses medidores estão conectados à internet e transmitem dados de consumo de energia em tempo real. Seu supervisor pede que você direcione o projeto para usar aprendizado de máquina para analisar esses dados de uso. Por que os algoritmos de aprendizado de máquina são ideais neste cenário?'),
(12, 'Para prever um valor de quantidade. use `___`.'),
(13, 'Por que o "naive Bayes" é chamado de ingênuo ("naive")?'),
(15, 'Como o aprendizado de máquina está relacionado à inteligência artificial?'),
(16, 'Como os algoritmos de aprendizado de máquina fazem previsões mais precisas?'),
(17, 'Você trabalha para uma seguradora. Qual projeto de aprendizado de máquina agregaria mais valor para a empresa?'),
(19, 'Qual é o motivo para não usar os mesmos dados tanto para o conjunto de treinamento quanto para o conjunto de testes?'),
(20, 'Sua universidade deseja usar algoritmos de aprendizado de máquina para ajudar a classificar as inscrições recebidas dos alunos. Um administrador pergunta se as decisões de admissão podem ser tendenciosas contra algum grupo específico, como as mulheres. Qual seria a melhor resposta?'),
(21, 'O que é empilhamento?'),
(22, 'Você deseja criar um sistema supervisionado de aprendizado de máquina que identifique fotos de gatinhos nas redes sociais. Para fazer isso, você coletou mais de 100 mil imagens de gatinhos. Como é chamada essa coleção de imagens?'),
(23, 'Você está trabalhando em um projeto que envolve agrupar imagens de cães diferentes. Você tira uma imagem e a identifica como sua imagem centróide. Que tipo de algoritmo de aprendizado de máquina você está usando?'),
(24, 'Sua empresa deseja que você crie um modelo interno de previsão de texto de e-mail para acelerar o tempo que os funcionários gastam escrevendo e-mails. O que você deveria fazer?'),
(25, 'Sua organização permite que as pessoas criem perfis profissionais online. Uma característica fundamental é a capacidade de criar grupos de pessoas que estão profissionalmente conectadas entre si. Que tipo de método de aprendizado de máquina é usado para criar esses clusters?'),
(27, 'A floresta aleatória é uma versão modificada e melhorada de qual técnica anterior?'),
(28, 'Mapas auto-organizáveis são redes neurais especializadas para que tipo de aprendizado de máquina?'),
(29, 'Qual afirmação sobre agrupamento K-means é verdadeira?'),
(30, 'Você criou um sistema de aprendizado de máquina que interage com seu ambiente e responde a erros e recompensas. Que tipo de sistema de aprendizado de máquina é esse?'),
(31, 'Sua equipe de ciência de dados deve construir um classificador binário, e o critério número um é a pontuação mais rápida possível na implantação. Pode até ser implantado em tempo real. Qual técnica produzirá um modelo que provavelmente será mais rápido para a equipe de implantação usar em novos casos?'),
(32, 'Sua equipe de ciência de dados deseja usar o algoritmo de classificação K-nearest neighbor. Alguém da sua equipe deseja usar um K de 25. Quais são os desafios dessa abordagem?'),
(33, 'Seu sistema de aprendizado de máquina está tentando descrever uma estrutura oculta de dados não rotulados. Como você descreveria esse método de aprendizado de máquina?'),
(34, 'Você trabalha para uma grande empresa de processamento de cartões de crédito que deseja criar promoções direcionadas para seus clientes. A equipe de ciência de dados criou um sistema de aprendizado de máquina que agrupa clientes que fizeram compras semelhantes e os divide com base na fidelidade do cliente. Como você descreveria essa abordagem de aprendizado de máquina?'),
(35, 'Você está usando K-nearest neighbor e tem K de 1. O que você provavelmente verá ao treinar o modelo?'),
(36, 'O viés e a variação do modelo de dados são um desafio para o aprendizado não supervisionado?'),
(37, 'Qual escolha é melhor para classificação binária?'),
(38, 'Com a programação tradicional, o programador normalmente insere comandos. Com o aprendizado de máquina, o programador insere'),
(39, 'Por que é importante que os algoritmos de aprendizado de máquina tenham acesso a dados de alta qualidade?'),
(40, 'No K-nearest neighbor, quanto mais próximo você estiver do vizinho, maior será a probabilidade de você'),
(41, 'No programa da HBO, Silicon Valley, um dos personagens cria um aplicativo móvel chamado Not Hot Dog. Funciona fazendo com que o usuário tire uma foto de comida com seu dispositivo móvel. Aí o app diz se a comida é cachorro-quente. Para criar o aplicativo, o desenvolvedor do software carregou centenas de milhares de fotos de cachorros-quentes. Como você descreveria esse tipo de aprendizado de máquina?'),
(42, 'Você trabalha para uma grande empresa farmacêutica cuja equipe de ciência de dados deseja usar algoritmos de máquina de aprendizagem não supervisionada para ajudar a descobrir novos medicamentos. Qual é a vantagem dessa abordagem?'),
(43, 'Em 2015, o Google criou um sistema de aprendizado de máquina que poderia vencer um humano no jogo Go. Acredita-se que este jogo extremamente complexo tenha mais possibilidades de jogo do que átomos no universo. A primeira versão do sistema venceu ao observar centenas de milhares de horas de jogo humano; a segunda versão aprendeu a jogar obtendo recompensas enquanto jogava contra si mesma. Como você descreveria essa transição para diferentes abordagens de aprendizado de máquina?'),
(44, 'A empresa de segurança para a qual você trabalha está pensando em adicionar algoritmos de aprendizado de máquina ao seu dispositivo de detecção de ameaças à rede de computadores. Qual é uma vantagem de usar o aprendizado de máquina?'),
(45, 'Você trabalha para um hospital que monitora a propagação comunitária de um vírus. O hospital criou um aplicativo smartwatch que carrega dados de temperatura corporal de centenas de milhares de participantes. Qual é a melhor técnica para analisar os dados?'),
(46, 'Muitos dos avanços no aprendizado de máquina vieram de `___` aprimorados.'),
(48, 'Naive Bayes analisa cada preditor **\_** e cria uma probabilidade que pertence a cada classe.'),
(49, 'Alguém em sua equipe de ciência de dados recomenda que você use árvores de decisão, Bayes ingênuo e K-vizinho mais próximo, tudo ao mesmo tempo, nos mesmos dados de treinamento, e então calcule a média dos resultados. Do que isso é um exemplo?'),
(50, 'Sua equipe de ciência de dados deseja usar o aprendizado de máquina para filtrar melhor as mensagens de spam. A equipe reuniu um banco de dados de 100 mil mensagens que foram identificadas como spam ou não spam. Se você estiver usando aprendizado de máquina supervisionado, como chamaria esse conjunto de dados?'),
(51, 'Você trabalha para um site que permite que os clientes vejam todas as suas imagens na Internet, enviando uma foto própria. Seu modelo de dados usa cinco características para combinar as pessoas com suas fotos: cor, olhos, gênero, óculos e pelos faciais. Seus clientes têm reclamado que recebem dezenas de milhares de fotos sem eles. Qual é o problema?'),
(52, 'Seu supervisor pede que você crie um sistema de aprendizado de máquina que ajudará seu departamento de recursos humanos a classificar os candidatos a empregos em grupos bem definidos. Que tipo de sistema você provavelmente recomendaria?'),
(53, 'Você e sua equipe de ciência de dados têm 1 TB de dados de exemplo. O que você normalmente faz com esses dados?'),
(54, 'Sua equipe de ciência de dados está trabalhando em um produto de aprendizado de máquina que pode atuar como oponente artificial em videogames. A equipe está usando um algoritmo de aprendizado de máquina que se concentra em recompensas: se a máquina fizer algumas coisas bem, ela melhorará a qualidade do resultado. Como você descreveria esse tipo de algoritmo de aprendizado de máquina?'),
(55, 'O modelo será treinado com dados em um único lote é conhecido como?'),
(56, 'Qual das alternativas a seguir NÃO é aprendizagem supervisionada?'),
(57, 'Suponha que gostaríamos de realizar agrupamento de dados espaciais, como a localização geométrica das casas. Desejamos produzir clusters de diversos tamanhos e formatos. Qual dos seguintes métodos é o mais apropriado?'),
(58, 'A função de erro mais adequada para descida gradiente usando regressão logística é'),
(59, 'Em comparação com a variância da Estimativa de Máxima Verossimilhança (MLE), a variância da estimativa do Máximo A Posteriori (MAP) é `___`'),
(60, '`___` refere-se a um modelo que não pode modelar os dados de treinamento nem generalizar para novos dados.'),
(62, 'O que significa ajustar mal o seu modelo de dados?'),
(63, 'Usuário asiático reclama que o modelo de reconhecimento facial da sua empresa não identifica corretamente suas expressões faciais. O que você deveria fazer?'),
(67, 'O novo conjunto de dados que você acabou de extrair parece exibir muitos valores ausentes. Que ação o ajudará a minimizar esse problema?'),
(68, 'Qual dos seguintes métodos pode ser usado como aprendizagem não supervisionada ou como técnica de redução de dimensionalidade?'),
(69, 'Qual é a principal motivação para usar funções de ativação em RNA?'),
(70, 'Qual função de perda se ajustaria melhor em uma aprendizagem supervisionada categórica (discreta)?'),
(76, 'Qual escolha é o melhor exemplo de dados rotulados?'),
(77, 'Em estatística, o que é definido como a probabilidade de um teste de hipótese encontrar um efeito – se houver um efeito a ser encontrado?'),
(78, 'Você deseja criar um algoritmo de aprendizado de máquina para identificar receitas de comida na web. Para fazer isso, você cria um algoritmo que analisa diferentes probabilidades condicionais. Portanto, se a postagem incluir a palavra **farinha**, tem uma probabilidade um pouco maior de ser uma receita. Se contiver **farinha** e _açúcar_, é ainda mais provável que seja uma receita. Que tipo de algoritmo você está usando?'),
(79, 'O que é aprendizagem preguiçosa ("lazy learning")?'),
(80, 'O que é aprendizagem por reforço Q-learning?'),
(81, 'Os dados em seu modelo têm baixo viés e baixa variância. Como você esperaria que os pontos de dados fossem agrupados no diagrama?'),
(82, 'Seu sistema de aprendizado de máquina está usando exemplos rotulados para tentar prever dados futuros, comparar esses dados com o resultado previsto e, em seguida, com o modelo. Qual é a melhor descrição deste método de aprendizado de máquina?'),
(83, 'No filme WarGames de 1983, o computador aprende como dominar o jogo de xadrez jogando contra si mesmo. Qual método de aprendizado de máquina o computador estava usando?'),
(84, 'Você está trabalhando com seu algoritmo de aprendizado de máquina em algo chamado probabilidade de predição de classe. Qual algoritmo você provavelmente está usando?'),
(85, 'Qual é a maneira mais eficaz de corrigir o ajuste insuficiente do seu modelo aos dados?'),
(86, 'Sua equipe de ciência de dados é frequentemente criticada por criar relatórios enfadonhos ou óbvios demais. O que você poderia fazer para ajudar a melhorar a equipe?'),
(87, 'Qual é a diferença entre dados não estruturados e estruturados?'),
(88, 'Você trabalha para uma startup que está tentando desenvolver uma ferramenta de software que fará a varredura na Internet em busca de fotos de pessoas usando ferramentas específicas. O executivo-chefe está muito interessado em usar algoritmos de aprendizado de máquina. O que você recomendaria como o melhor lugar para começar?'),
(89, 'No aprendizado de máquina supervisionado, os cientistas de dados muitas vezes enfrentam o desafio de equilibrar entre o ajuste insuficiente ou excessivo do seu modelo de dados. Freqüentemente, eles precisam ajustar o conjunto de treinamento para fazer melhores previsões. Como é chamado esse equilíbrio?'),
(90, 'O que é probabilidade condicional?'),
(91, 'Clustering K-means é que tipo de algoritmo de aprendizado de máquina?'),
(92, 'O que é modelagem de conjunto?'),
(93, 'Qual é a melhor definição de preconceito em seu modelo de dados?'),
(94, 'Qual projeto pode ser mais adequado para aprendizado de máquina supervisionado?'),
(95, 'Quando uma árvore de decisão é mais comumente usada?'),
(96, 'Uma organização proprietária de dezenas de shopping centers deseja criar um produto de aprendizado de máquina que utilize reconhecimento facial para identificar clientes. Qual é o principal desafio de desenvolver tal modelo?'),
(97, 'Qual dos seguintes algoritmos de aprendizado de máquina não é supervisionado?'),
(98, 'Calcular a média da saída de múltiplas árvores de decisão ajuda a::'),
(99, 'Para otimizar sua função objetivo, você está realizando uma descida gradiente em lote completo usando todo o conjunto de treinamento (não uma descida gradiente estocástica). É necessário embaralhar seu conjunto de treinamento?'),
(100, 'Você recebeu 1.000.000 de imagens e dividiu-as em 96%/2%/2% entre conjuntos de treinamento, desenvolvimento e teste. Você treinou seu modelo e analisou os resultados. Depois de trabalhar mais no problema, você decidiu corrigir os dados rotulados incorretamente no conjunto de desenvolvimento.'),
(101, 'Você está trabalhando em uma tarefa de classificação binária para classificar se uma imagem contém um gato ("1") ou não contém um gato ("0"). Que perda você escolheria minimizar para treinar um modelo?'),
(102, 'Você deseja criar um algoritmo de aprendizado de máquina que encontre as 100 principais pessoas que compartilharam fotos suas nas redes sociais. Qual é o melhor método de aprendizado de máquina para usar?'),
(103, 'O famoso cientista de dados Andrew Ng foi citado como tendo dito: “O aprendizado de máquina aplicado é basicamente engenharia de recursos”. O que é engenharia de recursos?'),
(104, 'No contexto do cálculo, o que é df/dx?'),
(105, 'O que é um modelo bem projetado/bem ajustado?'),
(106, 'A filtragem colaborativa baseada em **\_** ocorre quando uma pessoa recomenda um item semelhante a um item que ela comprou.'),
(107, 'Preencha os espaços em branco: Duas técnicas de imputação multivariadas são a imputação **\_** e a imputação **\_**.'),
(108, 'Você está trabalhando em um modelo de regressão usando a biblioteca Keras. Qual método da classe Model você usa para treinar o modelo?'),
(109, 'Qual é o objetivo da regularização no algoritmo K vizinhos mais próximos?'),
(111, 'Se você está pensando em usar algoritmos de aprendizado de máquina, a melhor coisa que você pode fazer hoje é garantir que você tenha qualidade **\_**.'),
(112, 'O diretor de diversidade da sua organização está preocupado com a falta de diversidade racial e de gênero em seu departamento de engenharia. Você será solicitado a criar um sistema supervisionado de aprendizado de máquina para ajudar a classificar centenas de milhares de novos pedidos de emprego. O departamento de recursos humanos insiste em usar dados internos de contratação. Quais são alguns dos perigos que você pode enfrentar?'),
(113, 'Em 2013, o projeto DeepMind do Google criou um algoritmo de aprendizado de máquina que poderia jogar um videogame Atari antigo, o Pong. O algoritmo ensinou a máquina a jogar criando uma série de recompensas. Cada vez que a máquina devolvia a bola com sucesso, a máquina recebia uma recompensa; cada vez que o adversário errava a bola, a máquina ganhava uma recompensa. Como você descreveria esse tipo de algoritmo de aprendizado de máquina?'),
(114, 'Uma organização proprietária de dezenas de shopping centers deseja criar um produto de aprendizado de máquina que utilize reconhecimento facial para identificar clientes. Qual é um dos principais desafios no desenvolvimento de tal produto?'),
(115, 'Qual é a diferença entre dados não estruturados e estruturados?'),
(116, 'Você trabalha para uma startup que está tentando desenvolver uma ferramenta de software que irá procurar na internet fotos de pessoas usando produtos específicos. O executivo-chefe está muito interessado em usar algoritmos de aprendizado de máquina. o que você recomendaria como o melhor lugar para começar?'),
(117, 'Qual é a definição de aprendizagem por reforço?'),
(118, 'A regressão de mínimos quadrados resolve um problema de estimativa de máxima verossimilhança em um modelo linear'),
(120, 'O total de tipos da camada em função de base radial em redes neurais é **\_\_**'),
(121, 'O que é um analisador de cima para baixo?'),
(122, 'Qual método de pesquisa expandirá o nó mais próximo do objetivo?'),
(123, 'O que é usado para melhorar o desempenho da pesquisa heurística?'),
(124, 'Para que normalmente é usado um analisador de frases?'),
(125, 'Qual das seguintes técnicas não pode ser usada para normalização na mineração de texto?'),
(126, 'Como você lida com dados ausentes ou corrompidos em um conjunto de dados?'),
(127, 'Quantos bits cabem em um byte?'),
(128, 'Quais foram os 3Vs que se iniciaram o Big Data?'),
(129, 'Qual a definição de Big Data?'),
(130, 'Quais dos 4 Vs que melhor se aplica a afirmativa: Dados são transferidos, armazenados e baixados em velocidades altíssimas!'),
(131, 'O Big Data so é aplicado nas redes sociais?'),
(132, 'Quando surgiu o Big Data?'),
(133, 'Big Data e Data Science são a mesma coisa?'),
(134, 'A definição "Sequência de atividade para cumprir uma determinada função do sistema" corresponde a:'),
(135, 'A definição "É a informação no nível atômico" corresponde a:'),
(136, 'Assinale a opção que apresenta um dado e conteúdo de dado, respectivamente:'),
(137, 'O dado "nome do aluno" é do tipo Natural?'),
(138, 'Data Science (Ciência de Dados) é uma área interdisciplinar que abrange:'),
(139, 'Assinale a alternativa que apresenta a definição correta de Inteligência Artificial:'),
(140, 'Os 4Vs do Big Data são:'),
(141, 'São algoritmos supervisionados'),
(142, 'São algoritmos não supervisionados'),
(143, 'A definição "consiste em encontrar padrões frequentes de associações entre os atributos de um conjunto de dados" corresponde a categoria de algoritmos de:'),
(144, 'A definição "associa a descrição de um objeto a uma classe" corresponde a categoria de algoritmos de:');


INSERT INTO PERGUNTA_OPCAO (ID, PERGUNTA_ID, DESCRICAO, CORRETA) VALUES
(1, 1, 'diagrama de classificação multiclasse', false),
(2, 1, 'regressão linear e gráficos de dispersão', true),
(3, 1, 'tabela dinâmica', false),
(4, 1, 'diagrama de cluster K-means', false),
(5, 2, 'O produto procuraria novos padrões em mensagens de spam.', false),
(6, 2, 'O produto poderia passar pela lista de palavras-chave muito mais rapidamente.', false),
(7, 2, 'O produto pode ter uma lista de palavras-chave muito mais longa.', false),
(8, 2, 'O produto pode encontrar mensagens de spam usando muito menos palavras-chave.', true),
(9, 3, 'cluster de dados', false),
(10, 3, 'Conjunto supervisionado', false),
(11, 3, 'grandes dados', false),
(12, 3, 'dados de teste', true),
(13, 4, 'padrões', false),
(14, 4, 'programas', false),
(15, 4, 'regras', false),
(16, 4, 'dados', true),
(17, 5, 'Estava sempre errado.', true),
(18, 5, 'Foi inconsistentemente errado.', false),
(19, 5, 'Estava consistentemente certo.', false),
(20, 5, 'Foi igualmente certo e errado.', false),
(21, 6, 'Encontre dados rotulados de dias ensolarados para que a máquina aprenda a identificar o mau tempo.', false),
(22, 6, 'Use o aprendizado não supervisionado para que a máquina procure anomalias em um enorme banco de dados meteorológicos.', false),
(23, 6, 'Crie um conjunto de treinamento de padrões incomuns e peça aos algoritmos de aprendizado de máquina para classificá-los.', false),
(24, 6, 'Crie um conjunto de treinamento com clima normal e faça a máquina procurar padrões semelhantes.', true),
(25, 7, 'regressão', false),
(26, 7, 'impulsionando', false),
(27, 7, 'ensacamento', false),
(28, 7, 'empilhamento', true),
(29, 8, 'Análise de regressão', true),
(30, 8, 'agrupamento K-means', false),
(31, 8, 'Grandes dados', false),
(32, 8, 'Aprendizagem não supervisionada', false),
(33, 9, 'um sistema de entrada de dados', false),
(34, 9, 'um sistema de armazém de dados', false),
(35, 9, 'um enorme repositório de dados', false),
(36, 9, 'um sistema de recomendação de produtos', true),
(37, 11, 'Os algoritmos ajudariam os medidores a acessar a internet.', false),
(38, 11, 'Os algoritmos irão melhorar a conectividade sem fio.', false),
(39, 11, 'Os algoritmos ajudariam sua organização a ver padrões dos dados.', true),
(40, 11, 'Ao usar algoritmos de aprendizado de máquina, você está criando um dispositivo IoT.', false),
(41, 12, 'regressão', true),
(42, 12, 'agrupamento', false),
(43, 12, 'classificação', false),
(44, 12, 'redução de dimensionalidade', false),
(45, 13, 'Ingenuamente assume que você não terá dados.', false),
(46, 13, 'Nem tenta criar previsões precisas.', false),
(47, 13, 'Ingenuamente assume que os preditores são independentes um do outro.', true),
(48, 13, 'Ingenuamente assume que todos os preditores dependem uns dos outros.', false),
(49, 15, 'A inteligência artificial se concentra na classificação, enquanto o aprendizado de máquina trata do agrupamento de dados.', false),
(50, 15, 'O aprendizado de máquina é um tipo de inteligência artificial que depende do aprendizado por meio de dados.', true),
(51, 15, 'A inteligência artificial é uma forma de aprendizado de máquina não supervisionado.', false),
(52, 15, 'Aprendizado de máquina e inteligência artificial são a mesma coisa.', false),
(53, 16, 'Os algoritmos normalmente executam servidores mais poderosos.', false),
(54, 16, 'Os algoritmos são melhores em ver padrões nos dados.', true),
(55, 16, 'Servidores de aprendizado de máquina podem hospedar bancos de dados maiores.', false),
(56, 16, 'Os algoritmos podem ser executados em dados não estruturados.', false),
(57, 17, 'Criar uma rede neural artificial que hospedaria o diretório da empresa.', false),
(58, 17, 'Use o aprendizado de máquina para prever melhor os riscos.', true),
(59, 17, 'Crie um algoritmo que consolide todas as suas planilhas do Excel em um data lake.', false),
(60, 17, 'Use aprendizado de máquina e big data para pesquisar requisitos salariais.', false),
(61, 19, 'Você quase certamente não se adequará ao modelo.', false),
(62, 19, 'Você escolherá o algoritmo errado.', false),
(63, 19, 'Talvez você não tenha dados suficientes para ambos.', false),
(64, 19, 'Você quase certamente ajustará demais o modelo.', true),
(65, 20, 'Os algoritmos de aprendizado de máquina são baseados em matemática e estatística e, portanto, por definição, serão imparciais.', false),
(66, 20, 'Não há como identificar vieses nos dados.', false),
(67, 20, 'Algoritmos de aprendizado de máquina são poderosos o suficiente para eliminar distorções dos dados.', false),
(68, 20, 'Todos os dados criados por humanos são tendenciosos e os cientistas de dados precisam levar isso em conta.', true),
(69, 21, 'As previsões de um modelo tornam-se as entradas de outro.', true),
(70, 21, 'Você usa diferentes versões de algoritmos de aprendizado de máquina.', false),
(71, 21, 'Você usa vários algoritmos de aprendizado de máquina para potencializar seus resultados.', false),
(72, 21, 'Você empilha seu conjunto de treinamento e teste juntos.', false),
(73, 22, 'dados de treinamento', true),
(74, 22, 'regressão linear', false),
(75, 22, 'grandes dados', false),
(76, 22, 'dados de teste', false),
(77, 23, 'reforço centróide', false),
(78, 23, 'K-nearest neighbor', false),
(79, 23, 'classificação binária', false),
(80, 23, 'agrupamento K-mean', true),
(81, 24, 'Incluir dados de e-mail de treinamento de todos os funcionários.', true),
(82, 24, 'Incluir dados de e-mail de treinamento de novos funcionários.', false),
(83, 24, 'Incluir dados de e-mail de treinamento de funcionários experientes.', false),
(84, 24, 'Incluir dados de e-mail de treinamento de funcionários que escrevem a maioria dos e-mails internos.', false),
(85, 25, 'aprendizado de máquina não supervisionado', true),
(86, 25, 'classificação binária', false),
(87, 25, 'aprendizado de máquina supervisionado', false),
(88, 25, 'aprendizagem por reforço', false),
(89, 27, 'árvores agregadas', false),
(90, 27, 'árvores impulsionadas', false),
(91, 27, 'árvores ensacadas', true),
(92, 27, 'árvores empilhadas', false),
(93, 28, 'aprendizagem semissupervisionada', false),
(94, 28, 'aprendizagem supervisionada', false),
(95, 28, 'aprendizagem por reforço', false),
(96, 28, 'aprendizagem não supervisionada', true),
(97, 29, 'No agrupamento K-means, os centróides iniciais às vezes são selecionados aleatoriamente.', true),
(98, 29, 'O agrupamento K-means é frequentemente usado em aprendizado de máquina supervisionado.', false),
(99, 29, 'O número de clusters é sempre selecionado aleatoriamente.', false),
(100, 29, 'Para ser preciso, você quer seus centróides fora do cluster.', false),
(101, 30, 'aprendizagem supervisionada', false),
(102, 30, 'aprendizagem semissupervisionada', false),
(103, 30, 'aprendizagem por reforço', true),
(104, 30, 'aprendizagem não supervisionada', false),
(105, 31, 'regressão logística', true),
(106, 31, 'KNN', false),
(107, 31, 'rede neural profunda', false),
(108, 32, 'Valores mais altos de K produzirão dados ruidosos.', false),
(109, 32, 'Valores mais altos de K diminuem o viés, mas aumentam a variância.', false),
(110, 32, 'Valores de K mais altos precisam de um conjunto de treinamento maior.', false),
(111, 32, 'Valores mais altos de K diminuem a variância, mas aumentam o viés.', true),
(112, 33, 'aprendizagem supervisionada', false),
(113, 33, 'aprendizagem não supervisionada', true),
(114, 33, 'aprendizagem por reforço', false),
(115, 33, 'aprendizagem semi-não supervisionada', false),
(116, 34, 'Utiliza aprendizagem não supervisionada para agrupar transações e aprendizagem não supervisionada para classificar os clientes.', true),
(117, 34, 'Ele usa apenas aprendizado de máquina não supervisionado.', false),
(118, 34, 'Utiliza aprendizagem supervisionada para criar clusters e aprendizagem não supervisionada para classificação.', false),
(119, 34, 'Utiliza aprendizagem por reforço para classificar os clientes.', false),
(120, 35, 'alta variância e baixo viés', true),
(121, 35, 'baixo viés e baixa variância', false),
(122, 35, 'baixa variância e alto viés', false),
(123, 35, 'alto viés e alta variância', false),
(124, 36, 'Não, o viés e a variância do modelo de dados são apenas um desafio com o aprendizado por reforço.', false),
(125, 36, 'Sim, o viés do modelo de dados é um desafio quando a máquina cria clusters.', true),
(126, 36, 'Sim, a variação do modelo de dados treina o algoritmo de aprendizado de máquina não supervisionado.', false),
(127, 36, 'Não, o viés e a variância do modelo de dados envolvem aprendizagem supervisionada.', false),
(128, 37, 'K-means', false),
(129, 37, 'Regressão logística', true),
(130, 37, 'Regressão linear', false),
(131, 37, 'Análise de Componentes Principais (PCA)', false),
(132, 38, 'aprendizagem supervisionada', false),
(133, 38, 'dados', true),
(134, 38, 'aprendizagem não supervisionada', false),
(135, 38, 'algoritmos', false),
(136, 39, 'Levará muito tempo para os programadores limparem dados ruins.', false),
(137, 39, 'Se os dados forem de alta qualidade, os algoritmos serão mais fáceis de desenvolver.', false),
(138, 39, 'Dados de baixa qualidade requerem muito mais poder de processamento do que dados de alta qualidade.', false),
(139, 39, 'Se os dados forem de baixa qualidade, você obterá resultados imprecisos.', true),
(140, 40, 'compartilham características comuns', true),
(141, 40, 'fazer parte do nó raiz', false),
(142, 40, 'tem uma conexão euclidiana', false),
(143, 40, 'fazer parte do mesmo cluster', false),
(144, 41, 'Aprendizado de máquina de reforço', false),
(145, 41, 'aprendizado de máquina não supervisionado', false),
(146, 41, 'aprendizado de máquina supervisionado', true),
(147, 41, 'aprendizado de máquina semissupervisionado', false),
(148, 42, 'Você poderá priorizar diferentes classes de medicamentos, como antibióticos.', false),
(149, 42, 'Você pode criar um conjunto de treinamento de medicamentos que gostaria de descobrir.', false),
(150, 42, 'Os algoritmos agruparão medicamentos com características semelhantes.', true),
(151, 42, 'Especialistas humanos podem criar classes de medicamentos para ajudar a orientar a descoberta.', false),
(152, 43, 'O sistema passou de aprendizagem supervisionada para aprendizagem por reforço.', true),
(153, 43, 'O sistema evoluiu de aprendizagem supervisionada para aprendizagem não supervisionada.', false),
(154, 43, 'O sistema evoluiu de aprendizagem não supervisionada9 para aprendizagem supervisionada.', false),
(155, 43, 'O sistema evoluiu de aprendizagem por reforço para aprendizagem não supervisionada.', false),
(156, 44, 'Poderia proteger melhor contra ameaças não descobertas.', true),
(157, 44, 'Provavelmente diminuiria os requisitos de hardware.', false),
(158, 44, 'Isso reduziria substancialmente o seu tempo de desenvolvimento.', false),
(159, 44, 'Aumentaria a velocidade do aparelho.', false),
(160, 45, 'Use o aprendizado por reforço para recompensar o sistema quando uma nova pessoa participa.', false),
(161, 45, 'Use aprendizado de máquina não supervisionado para agrupar pessoas com base em padrões que a máquina descobre.', false),
(162, 45, 'Use aprendizado de máquina supervisionado para classificar pessoas por dados demográficos.', false),
(163, 45, 'Use aprendizado de máquina supervisionado para classificar pessoas por temperatura corporal.', true),
(164, 46, 'Estatisticas', false),
(165, 46, 'dados estruturados', false),
(166, 46, 'disponibilidade', false),
(167, 46, 'algoritmos', true),
(168, 48, 'condicional', false),
(169, 48, 'multiclasse', false),
(170, 48, 'independente', true),
(171, 48, 'binário', false),
(172, 49, 'análise de regressão', false),
(173, 49, 'aprendizagem não supervisionada', false),
(174, 49, 'modelagem de alta variância', false),
(175, 49, 'modelagem de conjunto', true),
(176, 50, 'algoritmo de aprendizado de máquina', false),
(177, 50, 'conjunto de treinamento', true),
(178, 50, 'conjunto de teste de big data', false),
(179, 50, 'cluster de dados', false),
(180, 51, 'Você está superajustando o modelo aos dados', false),
(181, 51, 'Você precisa de um conjunto de treinamento menor', false),
(182, 51, 'Você está ajustando o modelo aos dados', true),
(183, 51, 'Você precisa de um conjunto de treinamento maior', false),
(184, 52, 'um sistema de aprendizado de máquina não supervisionado que agrupa os melhores candidatos.', false),
(185, 52, 'você não recomendaria um sistema de aprendizado de máquina para este tipo de projeto.', false),
(186, 52, 'uma rede neural artificial de aprendizagem profunda que depende de petabytes de dados de emprego.', false),
(187, 52, 'um sistema supervisionado de aprendizado de máquina que classifica os candidatos em grupos existentes.', true),
(188, 53, 'você o usa como seu conjunto de treinamento.', false),
(189, 53, 'Você rotula isso de big data.', true),
(190, 53, 'Você o divide em um conjunto de treinamento e um conjunto de teste.', false),
(191, 53, 'Você o usa como seu conjunto de teste.', false),
(192, 54, 'aprendizado de máquina semissupervisionado', false),
(193, 54, 'aprendizado de máquina supervisionado', false),
(194, 54, 'aprendizado de máquina não supervisionado', false),
(195, 54, 'aprendizagem por reforço', true),
(196, 55, 'Aprendizagem em lote', false),
(197, 55, 'Aprendizagem off-line', false),
(198, 55, 'A e B', true),
(199, 55, 'Nenhuma das acima', false),
(200, 56, 'Árvore de decisão', false),
(201, 56, 'Regressão linear', false),
(202, 56, 'PCA', true),
(203, 57, 'Árvores de decisão', false),
(204, 57, 'K-means agrupamento', false),
(205, 57, 'Clustering baseado em densidade', true),
(206, 57, 'Clustering baseado em modelo', false),
(207, 58, 'A função de entropia.', false),
(208, 58, 'O erro quadrático.', false),
(209, 58, 'A função de entropia cruzada.', true),
(210, 58, 'O número de erros.', false),
(211, 59, 'Mais alto', false),
(212, 59, 'mesmo', false),
(213, 59, 'Inferior', true),
(214, 60, 'bom ajuste', false),
(215, 60, 'sobreajuste', false),
(216, 60, 'subajuste', true),
(217, 60, 'todas as alternativas', false),
(218, 62, 'Há poucos dados em seu conjunto de treinamento.', false),
(219, 62, 'Há muitos dados em seu conjunto de treinamento.', false),
(220, 62, 'Não há muita variação, mas há um viés alto.', true),
(221, 62, 'Seu modelo tem baixo viés, mas alta variância.', false),
(222, 63, 'Inclua rostos asiáticos em seus dados de teste e treine novamente seu modelo.', false),
(223, 63, 'Treine novamente seu modelo com valores de hiperparâmetros atualizados.', false),
(224, 63, 'Treine novamente seu modelo com tamanhos de lote menores.', false),
(225, 63, 'Inclua rostos asiáticos em seus dados de treinamento e treine novamente seu modelo.', true),
(226, 67, 'Preenchimento inteligente de valores aleatórios controlados', false),
(227, 67, 'Substitua os valores ausentes pela média de todas as amostras', false),
(228, 67, 'Remover amostras defeituosas', false),
(229, 67, 'Imputação', true),
(230, 68, 'SVM', false),
(231, 68, 'PCA', true),
(232, 68, '- [ ]LDA', false),
(233, 68, 'TSNE', false),
(234, 69, 'Captura de padrões não lineares complexos', true),
(235, 69, 'Transformando valores contínuos em valores "ON" (1) ou "OFF" (0)', false),
(236, 69, 'Ajuda a evitar o problema do gradiente de desaparecimento/explosão', false),
(237, 69, 'Sua capacidade de ativar cada neurônios individualmente.', false),
(238, 70, 'perda de kullback-leibler (KL)', false),
(239, 70, 'Entropia cruzada Binária', true),
(240, 70, 'Erro Quadrático Médio (MSE)', false),
(241, 70, 'Qualquer perda L2', false),
(242, 76, 'uma planilha', true),
(243, 76, '20.000 mensagens de correio de voz gravadas', false),
(244, 76, '100.000 imagens de automóveis', false),
(245, 76, 'centenas de gigabytes de arquivos de áudio', false),
(246, 77, 'confiança', false),
(247, 77, 'alfa', false),
(248, 77, 'potência', true),
(249, 77, 'significância', false),
(250, 78, 'classificador Bayes ingênuo', true),
(251, 78, 'K-vizinho mais próximo', false),
(252, 78, 'classificação multiclasse', false),
(253, 78, 'árvore de decisão', false),
(254, 79, 'quando os algoritmos de aprendizado de máquina fazem a maior parte da programação', false),
(255, 79, 'quando você não faz nenhuma limpeza de dados', false),
(256, 79, 'quando o aprendizado acontece continuamente', true),
(257, 79, 'quando você executa seu cálculo em uma grande instância no início', false),
(258, 80, 'aprendizado de máquina supervisionado com recompensas', false),
(259, 80, 'um tipo de aprendizagem não supervisionada que depende fortemente de um modelo bem estabelecido', false),
(260, 80, 'um tipo de aprendizagem por reforço onde a precisão se degrada com o tempo', false),
(261, 80, 'um tipo de aprendizagem por reforço que se concentra em recompensas', true),
(262, 81, 'Eles seriam agrupados firmemente no resultado previsto.', true),
(263, 81, 'Eles estariam agrupados, mas longe do previsto.', false),
(264, 81, 'Eles estariam espalhados pelo resultado previsto.', false),
(265, 81, 'Eles seriam espalhados longe do resultado previsto.', false),
(266, 82, 'aprendizagem não supervisionada', false),
(267, 82, 'aprendizagem semissupervisionada', false),
(268, 82, 'aprendizagem supervisionada', true),
(269, 82, 'aprendizagem de semi-reforço', false),
(270, 83, 'aprendizagem binária', false),
(271, 83, 'aprendizagem supervisionada', false),
(272, 83, 'aprendizagem não supervisionada', false),
(273, 83, 'aprendizagem por reforço', true),
(274, 84, 'classificação binária multiclasse', false),
(275, 84, 'naive Bayes', true),
(276, 84, 'classificação não supervisionada', false),
(277, 84, 'análise de árvore de decisão', false),
(278, 85, 'Criar clusters de treinamento', false),
(279, 85, 'Remover preditores', false),
(280, 85, 'Use aprendizagem por reforço', false),
(281, 85, 'Adicionar mais preditores', true),
(282, 86, 'Sugira que a equipe provavelmente está ajustando o modelo aos dados.', false),
(283, 86, 'Sugira que a aprendizagem não supervisionada levará a resultados mais interessantes.', false),
(284, 86, 'Certifique-se de que eles estão escolhendo os algoritmos de aprendizado de máquina corretos.', false),
(285, 86, 'Incentive a equipe a fazer perguntas mais interessantes.', true),
(286, 87, 'Dados não estruturados são sempre texto.', false),
(287, 87, 'Dados não estruturados são muito mais fáceis de armazenar.', false),
(288, 87, 'Os dados estruturados têm tipos de dados claramente definidos.', true),
(289, 87, 'Os dados estruturados são muito mais populares.', false),
(290, 88, 'Usando um algoritmo de aprendizado de máquina não supervisionado para agrupar todas as fotografias.', false),
(291, 88, 'Crie um data lake com um algoritmo de aprendizado de máquina não supervisionado.', false),
(292, 88, 'Use uma combinação de aprendizado de máquina supervisionado e não supervisionado para criar clusters de dados definidos por máquina.', false),
(293, 88, 'Use aprendizado de máquina supervisionado para classificar fotografias com base em um conjunto de treinamento predeterminado.', true),
(294, 89, 'o desafio abaixo/acima', false),
(295, 89, 'equilíbrio entre classificação de cluster', false),
(296, 89, 'compensação entre viés e variância', true),
(297, 89, 'o desafio do conjunto de treinamento multiclasse', false),
(298, 90, 'a probabilidade de que fazer uma coisa tenha impacto em outra coisa', true),
(299, 90, 'a probabilidade de que certas condições sejam atendidas', false),
(300, 90, 'a probabilidade de que, com base em certas condições, algo sempre estará incorreto', false),
(301, 90, 'a probabilidade de algo ser a resposta correta', false),
(302, 91, 'reforço', false),
(303, 91, 'supervisionado', false),
(304, 91, 'sem supervisão', true),
(305, 91, 'classificação', false),
(306, 92, 'quando você cria um conjunto de seu conjunto de dados de treinamento e teste', false),
(307, 92, 'quando você cria um conjunto de servidores diferentes para executar os algoritmos', false),
(308, 92, 'quando você encontra o melhor algoritmo para o seu conjunto', false),
(309, 92, 'quando você usa vários conjuntos de algoritmos de aprendizado de máquina', true),
(310, 93, 'Viés ocorre quando seus valores previstos estão dispersos.', false),
(311, 93, 'Viés é a diferença entre o valor previsto e o resultado.', true),
(312, 93, 'Viés é quando seus dados estão errados por diferentes motivos.', false),
(313, 93, 'Bias é quando seus valores estão sempre errados na mesma porcentagem.', false),
(314, 94, 'limpeza de dados', false),
(315, 94, 'prever uma pontuação de risco', true),
(316, 94, 'software de declaração de impostos', false),
(317, 94, 'consolidação de planilhas', false),
(318, 95, 'com produtos de big data', false),
(319, 95, 'para desafios de classificação binária de aprendizado de máquina supervisionado', true),
(320, 95, 'para encontrar o melhor cluster de dados', false),
(321, 95, 'para determinar "Q" na aprendizagem por reforço de Q-learning', false),
(322, 96, 'a maioria dos modelos de aprendizado de máquina não são projetados para vídeo', false),
(323, 96, 'pode ser antiético para a empresa identificar pessoas sem o seu consentimento', true),
(324, 96, 'será difícil decidir entre aprendizagem supervisionada e não supervisionada', false),
(325, 96, 'a imagem no vídeo não teria qualidade suficiente para identificar indivíduos', false),
(326, 97, 'Floresta aleatória', false),
(327, 97, 'k-nearest neighbors', false),
(328, 97, 'Máquinas de vetores de suporte', false),
(329, 97, 'K-means', true),
(330, 98, 'Aumentar a variância', false),
(331, 98, 'Aumentar o viés', false),
(332, 98, 'Diminuir variância', true),
(333, 98, 'Diminuir preconceito', false),
(334, 99, 'Sim. Caso contrário, a otimização oscilará em torno do mínimo no final do treinamento.', false),
(335, 99, 'Sim, para ajudar o modelo a generalizar para o conjunto de dados de teste.', false),
(336, 99, 'Não, não é necessário porque o conjunto de dados já pode ser considerado embaralhado no processo de coleta de dados.', false),
(337, 99, 'Não, porque cada atualização passa por todo o conjunto de dados de qualquer maneira e a ordem não importa.', true),
(338, 100, 'Você também deve corrigir os dados rotulados incorretamente no conjunto de testes, para que os conjuntos dev e de teste ainda venham da mesma distribuição.', true),
(339, 100, 'Você também deve corrigir os dados rotulados incorretamente no conjunto de treinamento para evitar que seu conjunto de treinamento seja ainda mais diferente do seu conjunto de desenvolvimento.', false),
(340, 100, 'Você não deve corrigir os dados rotulados incorretamente no conjunto de testes, porque o conjunto de testes deve refletir a distribuição de dados do mundo real.', false),
(341, 100, 'Se você deseja corrigir dados rotulados incorretamente, você deve fazê-lo em todos os três conjuntos (treinar/dev/teste) para manter distribuições semelhantes.', false),
(342, 101, 'L = y log y^ + (1-y) log (1- y^)', false),
(343, 101, 'L = - y log y^ - (1-y) log (1- y^)', true),
(344, 101, 'eu = || y - y^ ||22', false),
(345, 101, 'eu = || y - y^ ||22 + constante', false),
(346, 102, 'aprendizagem por reforço', false),
(347, 102, 'classificação binária', true),
(348, 102, 'K-vizinho mais próximo', false),
(349, 102, 'aprendizagem não supervisionada', false),
(350, 103, 'extrair novos recursos de dados da web', false),
(351, 103, 'criando novas variáveis combinando e modificando as variáveis originais', true),
(352, 103, 'projetar novos recursos de usuário inovadores para adicionar ao software', false),
(353, 103, 'usando aprendizado profundo para encontrar recursos nos dados', false),
(354, 104, 'a função de previsão', false),
(355, 104, 'a derivada de f de x', true),
(356, 104, 'a derivada de x', false),
(357, 104, 'equivalente a f dividido por x', false),
(358, 105, 'aquele que foi treinado e testado com os mesmos dados', false),
(359, 105, 'aquele que possui um alto grau de precisão e é capaz de prever resultados com precisão', true),
(360, 105, 'aquele que foi treinado com dados de treinamento rotulados', false),
(361, 105, 'aquele que foi treinado com um conjunto exaustivo de todas as condições e permutações nos dados de treinamento', false),
(362, 106, 'História', false),
(363, 106, 'Item', true),
(364, 106, 'Semelhança', false),
(365, 106, 'Comprar', false),
(366, 107, 'supervisionado, não supervisionado', false),
(367, 107, 'iterativo, KNN', true),
(368, 107, 'semelhança, regressiva', false),
(369, 107, 'normalizado, dimensionado', false),
(370, 108, 'prever', false),
(371, 108, 'compilar', false),
(372, 108, 'ajuste', true),
(373, 108, 'get_weights', false),
(374, 109, 'normalizar os pontos de dados para que possam ser comparados entre si', false),
(375, 109, 'usando um modelo de linha reta para fazer previsões com base em dados de treinamento', false),
(376, 109, 'encontrar a inclinação da reta que representa o modelo', false),
(377, 109, 'tornando os limites de decisão mais regulares', true),
(378, 111, 'dados', true),
(379, 111, 'processadores', false),
(380, 111, 'rede', false),
(381, 111, 'técnicas estatísticas', false),
(382, 112, 'Haverá muitos dados para sua rede neural artificial processar com eficiência.', false),
(383, 112, 'Os sistemas de aprendizado de máquina não podem definir a diversidade, portanto não há como usá-los para melhorar as contratações.', false),
(384, 112, 'Sistemas de aprendizado de máquina não podem ser usados com este tipo de dados.', false),
(385, 112, 'Se o sistema utilizar dados internos, poderá amplificar qualquer preconceito existente na contratação.', true),
(386, 113, 'aprendizado de máquina de big data.', false),
(387, 113, 'A Boa e Velha Inteligência Artificial (GOFAI).', false),
(388, 113, 'aprendizagem por reforço.', true),
(389, 113, 'aprendizagem supervisionada.', false),
(390, 114, 'As imagens do vídeo não teriam qualidade suficiente para identificar indivíduos.', false),
(391, 114, 'Seria difícil decidir entre aprendizagem supervisionada e não supervisionada.', false),
(392, 114, 'Pode ser antiético para a empresa identificar pessoas sem o seu consentimento.', true),
(393, 114, 'A maioria dos algoritmos de aprendizado de máquina não são projetados para vídeo.', false),
(394, 115, 'Dados não estruturados são muito mais fáceis de armazenar.', false),
(395, 115, 'Os dados estruturados têm tipos de dados claramente definidos.', true),
(396, 115, 'Dados não estruturados são sempre texto.', false),
(397, 115, 'Os dados estruturados são muito mais populares.', false),
(398, 116, 'Crie um data lake com um algoritmo de aprendizado de máquina não supervisionado.', false),
(399, 116, 'Usando um algoritmo de aprendizado de máquina não supervisionado para agrupar todas as fotografias', false),
(400, 116, 'Use aprendizado de máquina supervisionado para classificar fotografias com base em um conjunto de treinamento predeterminado.', true),
(401, 116, 'Use uma combinação de aprendizado de máquina supervisionado e não supervisionado para criar clusters de dados definidos por máquina.', false),
(402, 117, 'A máquina itera através de diferentes modelos para melhorar continuamente o resultado.', true),
(403, 117, 'O desenvolvedor reforça o que já sabe.', false),
(404, 117, 'A máquina reforça a aprendizagem supervisionada.', false),
(405, 117, 'Trata-se de reforçar dados desconhecidos.', false),
(406, 118, 'Verdadeiro', true),
(407, 118, 'Falso', false),
(408, 120, '1', false),
(409, 120, '2', false),
(410, 120, '3', true),
(411, 120, '4', false),
(412, 121, 'Começa levantando a hipótese de uma frase (o símbolo S) e prevendo sucessivamente os constituintes de nível inferior até que símbolos pré-terminais individuais sejam escritos', true),
(413, 121, 'Começa formulando a hipótese de uma frase (o símbolo S) e prevendo sucessivamente os constituintes de nível superior até que símbolos pré-terminais individuais sejam escritos', false),
(414, 121, 'Começa levantando hipóteses sobre constituintes de nível inferior e prevendo sucessivamente uma frase (o símbolo S)', false),
(415, 121, 'Começa levantando hipóteses sobre constituintes de nível superior e prevendo sucessivamente uma frase (o símbolo S)', false),
(416, 122, 'Melhor primeira pesquisa', false),
(417, 122, 'Pesquisa gananciosa da melhor primeira', true),
(418, 122, 'Uma pesquisa', false),
(419, 122, 'Nenhum dos mencionados', false),
(420, 123, 'Qualidade dos nós', false),
(421, 123, 'Qualidade da função heurística', true),
(422, 123, 'Forma simples de nós', false),
(423, 123, 'Nenhum dos mencionados', false),
(424, 124, 'É usado para analisar frases para verificar se elas são compatíveis com utf-8.', false),
(425, 124, 'É usado para analisar sentenças para derivar suas estruturas de árvore sintática mais prováveis.', true),
(426, 124, 'É usado para analisar frases para atribuir tags POS a todos os tokens.', false),
(427, 124, 'É usado para verificar se as sentenças podem ser analisadas em tokens significativos.', false),
(428, 125, 'Derivação', false),
(429, 125, 'Lematização', false),
(430, 125, 'Parar remoção de palavras', true),
(431, 125, 'Nenhuma das acima', false),
(432, 126, 'Eliminar linhas ou colunas ausentes', false),
(433, 126, 'Substitua os valores ausentes por média/mediana/moda', false),
(434, 126, 'Atribua uma categoria exclusiva aos valores ausentes', false),
(435, 126, 'Todas as opções acima', true),
(436, 127, '8bits', true),
(437, 127, '1 bit', false),
(438, 127, '12 bits', false),
(439, 128, 'Valor, volume e veracidade.', false),
(440, 128, 'Variedade, valor e veracidade.', false),
(441, 128, 'Volume, velocidade e variedade.', true),
(442, 129, 'Apenas todos os dados dos seus celulares.', false),
(443, 129, 'Serve para organizar dados de forma simples e organizada.', false),
(444, 129, 'Serve para organizar e coletar o entendimento do crescente volume de dados por segundo.', true),
(445, 130, 'Velocidade', true),
(446, 130, 'Volume', false),
(447, 130, 'Valor', false),
(448, 130, 'Veracidade', false),
(449, 131, 'Falso. É usado também nas indústrias, como: no monitoramento de equipamentos em tempo real, na identificação de erros, agregação de informações em diversas fontes ligadas a fornecedores, empresas entre outros.', true),
(450, 131, 'Verdadeiros. O Big Data só se aplica nos dados gerados das redes sociais.', false),
(451, 132, '1997.', true),
(452, 132, '1888.', false),
(453, 132, '1789.', false),
(454, 133, 'Verdadeiro', false),
(455, 133, 'Falso', true),
(456, 134, 'Dado', false),
(457, 134, 'Informação', false),
(458, 134, 'Conhecimento', false),
(459, 134, 'Processo', true),
(460, 135, 'Dado', true),
(461, 135, 'Informação', false),
(462, 135, 'Conhecimento', false),
(463, 135, 'Sabedoria', false),
(464, 136, 'Data de contratação de Professor e 22/02/2019', true),
(465, 136, 'Natural e Artificial', false),
(466, 136, 'Calculado/Derivado e Valor total da compra', false),
(467, 136, 'Rua Comendador Martins, 52, Vila Mathias, Santos-SP e Quantidade de Alunos Matriculados', false),
(468, 137, 'Falso', false),
(469, 137, 'Verdadeiro', true),
(470, 138, 'Administração de empresas', false),
(471, 138, 'Ciência da computação +  Matemática e estatística', true),
(472, 138, 'Educação', false),
(473, 139, 'Possibilita que as máquinas aprendam com a experiência, ajustem-se a novas entradas e realizem tarefas semelhantes às humanas.', true),
(474, 139, 'Ciência que surgiu com a necessidade de lidarmos com a enorme quantidade de dados e informações geradas por nossas ações em conjunto com algum artefato.', false),
(475, 139, 'Consiste apenas na criação de robôs humanóides.', false),
(476, 139, 'Pode ser definida com 4Vs: Volume, Velocidade, Variedade e Valor.', false),
(477, 140, 'Velocidade Volume Valor Variedade', true),
(478, 140, 'Volume Visão Velocidade Valor', false),
(479, 140, 'Valor Visão Volume Velocidade', false),
(480, 140, 'Variedade Visão Valor Volume', false),
(481, 141, 'Associação', false),
(482, 141, 'Sumarização', false),
(483, 141, 'Regressão e Classificação', true),
(484, 141, 'Agrupamento', false),
(485, 142, 'Sumarização e Classificação', false),
(486, 142, 'Agrupamento Associação e Sumarização', true),
(487, 142, 'Sumarização e Regressão', false),
(488, 143, 'Classificação', false),
(489, 143, 'Associação', true),
(490, 143, 'Sumarização', false),
(491, 143, 'Agrupamento', false),
(492, 144, 'Sumarização', false),
(493, 144, 'Associação', false),
(494, 144, 'Classificação', true),
(495, 144, 'Agrupamento', false);

insert into quiz_perguntas
select 1, p.id from pergunta p